# Generated by Django 5.2.5 on 2025-08-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pais",
            options={
                "ordering": ["nombre"],
                "verbose_name": "país",
                "verbose_name_plural": "países",
            },
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pais_origen_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cliente.pais",
                verbose_name="País de origen",
            ),
        ),
    ]
