# Generated by Django 5.2.5 on 2025-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_alter_pais_options_alter_cliente_pais_origen_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente", old_name="nacimiento", new_name="fecha_nacimiento",
        ),
        migrations.RemoveField(model_name="cliente", name="pais_origen_id",),
        migrations.AddField(
            model_name="cliente",
            name="posicion1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="posicion2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
