# Generated by Django 5.2.5 on 2025-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0003_rename_nacimiento_cliente_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
