# Generated by Django 5.2.5 on 2025-10-20 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0006_add_equipo_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="email",),
        migrations.RemoveField(model_name="cliente", name="fecha_nacimiento",),
        migrations.AlterField(
            model_name="cliente",
            name="posicion1",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="posicion2",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.equipo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
