# Generated by Django 5.2.5 on 2025-10-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cliente",
            "0007_remove_cliente_email_remove_cliente_fecha_nacimiento_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="creador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
