# Generated by Django 5.2.7 on 2025-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0008_equipo_creador"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos_equipos/"),
        ),
    ]
