# Generated by Django 5.2.7 on 2025-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0009_equipo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="apodo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
