# Generated by Django 5.2.5 on 2025-08-29 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductoCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="descripcion",
                    ),
                ),
                ("precio", models.FloatField()),
                ("stock", models.IntegerField()),
            ],
            options={
                "verbose_name": "ProductoCategoria",
                "verbose_name_plural": "ProductoCategorias",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("unidad_medida", models.CharField(max_length=50)),
                ("stock", models.IntegerField()),
                ("precio", models.FloatField()),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="descripcion",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        null=True,
                        verbose_name="fecha de actualizacion",
                    ),
                ),
                (
                    "categoria_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="producto.productocategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["id"],
            },
        ),
    ]
